#
# This workflow will run all the normal static tests (linting, unit, etc.) and
# make sure the build completes successfully.
#

name: test

on:
  push:
    branches: [ '*', '*/*' ]

jobs:
  build:
    environment: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x, 18.x, 20.x ]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
      # We can run the example script through npm:
    - run: npm run example-script
      # But there's no npm funny business, we can run it through Node.js like normal:
    - run: node script/example-script.js
      # Make sure we can build and execute the code:
    - run: npm run build
    - run: node deploy/server/build/main.js
